server:
  port: 8081

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .html

  datasource:
    url: "jdbc:postgresql://34.95.230.228:5432/chat"
    username: postgres
    password: postgres

  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
